### ISSUE TITLE
Behavior of chromium with fcitx5(Japanese input system)

### ISSUE THREAD

**Issue by 1m-N00b** [cyrinux/hyprland-autoname-workspaces#12]
Thanks for such a great project!
I am also a fan and user of maximbaz's dotfiles and I recently migrated to hyprland-autoname-workspaces as well. Config is same like [this](https://github.com/maximbaz/dotfiles/blob/master/.config/hyprland-autoname-workspaces/config.toml)

So I'm asking for your advice.
I am Japanese and use fcitx5, a Japanese input software, but only chromium recognizes suggestions as follows. I would like to disable it somehow because it flickers every time I type.
![record_1677691756](https://user-images.githubusercontent.com/59286911/222216962-af1277da-e3d7-4838-af96-0e29fe7adcc5.gif)

By the way, this does not happen with firefox, kitty terminal, code oss, etc. Example: firefox
![firefox](https://user-images.githubusercontent.com/59286911/222212013-84c8cd81-8166-4e87-9501-3ac11c9a85b6.gif)

**Comment by maximbaz** [comment]
Hey 👋 Do you think you could catch the output of `hyprctl clients`? For example run `sleep 5 && hyprctl clients` and try to get that second icon on waybar 😉 By looking at it we might identify something about it, and use it to hide that icon later on.

**Comment by cyrinux** [comment]
Hey @1m-N00b ,
can you post me a `$ hyprctl clients -j | jq .` please before and after typing in the chromium search bar?

**Comment by 1m-N00b** [comment]
`sleep 5 && hyprctl clients -j | jq .` like this:
```[
  {
    "address": "0x2b00e690",
    "at": [
      967,
      7
    ],
    "size": [
      946,
      1041
    ],
    "workspace": {
      "id": 1,
      "name": "1:   "
    },
    "floating": false,
    "monitor": 0,
    "class": "chromium",
    "title": "新しいタブ - Chromium",
    "pid": 487474,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
  },
  {
    "address": "0x2b00d490",
    "at": [
      7,
      7
    ],
    "size": [
      946,
      1041
    ],
    "workspace": {
      "id": 1,
      "name": "1:   "
    },
    "floating": false,
    "monitor": 0,
    "class": "kitty",
    "title": "sleep 5 && hyprctl clients -j | jq .",
    "pid": 497524,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
  },
  {
    "address": "0x2add9820",
    "at": [
      223,
      66
    ],
    "size": [
      115,
      62
    ],
    "workspace": {
      "id": 1,
      "name": "1:   "
    },
    "floating": true,
    "monitor": 0,
    "class": "fcitx",
    "title": "Fcitx5 Input Window",
    "pid": 1371,
    "xwayland": true,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
  }
]``

**Comment by cyrinux** [comment]
Thanks @1m-N00b .
I'm polishing a fix that will allow you to exclude fcitx.

**Comment by cyrinux** [comment]
You did a good temporary hack by setting fctix icon to void, but it will be better optimize by exclude the exclude list then.

**Comment by cyrinux** [comment]
@1m-N00b could you please try the new version ?
You have to add to your config:

```
[exclude]
fcitx = ""
```

Also, after a first run of the app, if you don't migrate the config manually, you will add `[icons]` as first line.

**Comment by cyrinux** [comment]
@1m-N00b you have to use `fcitx = "*"` to exclude fcitx window with the last version please 😉
