### ISSUE TITLE
--verbose switch

### ISSUE THREAD

**Issue by pbosab** [cyrinux/hyprland-autoname-workspaces#18]
Hi,

just a thing that came into my mind while playing today with autoname.

**Describe the solution you'd like**
add a switch, maybe --verbose, and output something like:
opened "window class"
closed "window class"
etc...
in case of dedup:
opened "window class1"
opened "window class2"
opened "window class1" -- duplicate
etc..

**Additional context**
would be easier to identify classes without hyprctl

thanks!

**Comment by cyrinux** [comment]
Thanks for the idea 💡

**Comment by cyrinux** [comment]
Can you give a try ? I did simple.

**Comment by pbosab** [comment]
mate you are awesome.

it works, just a note:
when i open a window, it says all the opened windows: is it possible to see only the last one? or maybe --verbose 1 or --verbose 2 to switch between these modes?

and while playing with this noticed a problem, but i'll open a bug just to bother you :rofl:

**Comment by cyrinux** [comment]
It's possible but looks like a lot of code to do for just verbose. For sure I can do better but need to studies more than few seconds how to do this 😅

**Comment by pbosab** [comment]
atm my QOL while setting autoname up, is surely better and faster :) so many many thanks!

**Comment by cyrinux** [comment]
I close this issue, I will try to make better later 😉
