### ISSUE TITLE
[BUG] menu identified as windows

### ISSUE THREAD

**Issue by pbosab** [cyrinux/hyprland-autoname-workspaces#19]
**Describe the bug**
as in title, look at the video here: https://streamable.com/uu1mj1

**Expected behavior**
menu to no appear in the window list.

**Comment by cyrinux** [comment]
Can you pastebin me the output of the following command? Run it and do your steam menu tests.

```
while true; do hyprctl clients -j | jq .; sleep .5; done
```

**Comment by pbosab** [comment]
mh, is this what you were looking for:
https://pastebin.com/XYR3S0WA

**Comment by cyrinux** [comment]
Thanks, weeeirrrddd ... I can only see the empty class which can cause this, but we already ignore them 🤔

**Comment by cyrinux** [comment]
Is it well the "tray" module of waybar with the colored icon ?
Do you still have the glitch with `--dedup` enable ?

**Comment by cyrinux** [comment]
https://github.com/cyrinux/hyprland-autoname-workspaces/pull/20

**Comment by pbosab** [comment]
will try it as soon as i get home! thanks in the meantime!

**Comment by cyrinux** [comment]
@pbosab can you rebuild again ? I push a fix. You have to use `*` as title now to exclude a whole class.

`"Steam" = "",` will exclude window with Steam class and empty title.
`"Steam" = "*",` will exclude all Steam window.

**Comment by pbosab** [comment]
awesome! works. as always, thanks!
