### ISSUE TITLE
[BUG] Crash on group creation 

### ISSUE THREAD

**Issue by MathisP75** [cyrinux/hyprland-autoname-workspaces#21]
Creating a group in hyprland causes a crash with message:

```
thread "main" panicked at 'called 'Result:: unwrap() on an 'Err value: SerdeError(Error ("invalid type: string \"0x419ad760\", expected struct Client", line: 39, column: 28))", src/renamer/mod.rs:32:38
```

Using hyprland-nvidia

**Comment by cyrinux** [comment]
Hi @MathisP75 , can you pastebin me your config please?

**Comment by MathisP75** [comment]
I installed is using the AUR

The output is `hyprland-autoname-workspaces 0.3.6`

My config:

`[icons]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"DEFAULT" = ""
"kitty" = ""
"firefox" = ""
"code-oss" = "󰨞"
"org.pwmt.zathura" = ""
"thunar" = ""
"Webcord" = "󰙯"
"com.obsproject.Studio" = "󰻂"
"spotify" = ""
"Joplin" = "󱞁"
"Gimp-2.10" = ""

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
class = "title"`

**Comment by cyrinux** [comment]
Hmm 🤔 Do you well use the Unicode char for your emoji?

**Comment by cyrinux** [comment]
Sorry I can't reproduce,, the config you give me works for me. Is it really the full config you use ?
Can you maybe find what config line make it crash by putting in comment half of the icons list ?
 Is it reproducible ?

**Comment by cyrinux** [comment]
Ha, I reproduce now, it feel like the `hyprland-rs` doesn't know well the Clients struct when some window are toggle. I will try to fix this.

**Comment by cyrinux** [comment]
@MathisP75 tell me how it goes. It's fix.

**Comment by MathisP75** [comment]
Seems to be fixed!

**Comment by MathisP75** [comment]
Thank you!
