### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by StarsetKnight** [cyrinux/hyprland-autoname-workspaces#22]
When trying to do `systemctl enable --now hyprland-autoname-workspaces.service` to start the service it gives the error `Failed to enable unit: Unit file hyprland-autoname-workspaces.service does not exist.` And fails to start the service.
Running Arch Linux with kernel `6.2.8-arch1-1`, `hyprland-nvidia-git` and `waybar-hyprland-git` and `hyprland-autoname-workspaces 0.3.7`. I used the AUR package `hyprland-autoname-workspaces-git`.

**Comment by cyrinux** [comment]
Good catch, it is a little doc typo.

```systemctl --user enable --now hyprland-autoname-workspaces.service```
