### ISSUE TITLE
[BUG] empty titles exclude will also exclude classes with actual titles

### ISSUE THREAD

**Issue by xzsk2** [cyrinux/hyprland-autoname-workspaces#33]
**Describe the bug**
```
[exclude]
Alacritty = ""
```

this should ignore any "Alacritty" classes with empty titles

but `hyprland-autoname-workspaces --verbose` shows

```
- window: class 'Alacritty' with title 'hyprland-autoname-workspaces --verbose' is exclude
```

and `hyprctl clients` outputs

```
Window cacdce40 -> hyprland-autoname-workspaces --verbose:
	mapped: 1
	hidden: 0
	at: 486,565
	size: 468,508
	workspace: 1 (1: )
	floating: 0
	monitor: 0
	class: Alacritty
	title: hyprland-autoname-workspaces --verbose
	initialClass: Alacritty
	initialTitle: Alacritty
	pid: 200442
	xwayland: 0
	pinned: 0
	fullscreen: 0
	fullscreenmode: 0
	fakefullscreen: 0
	grouped: 0
	swallowing: 0
```

somehow it's ignored any "Alacritty" classes with titles

**Linux Distro (please complete the following information):**
 - Arch Linux 6.2.9

**Program version?**
 - e720848

**Comment by cyrinux** [comment]
@xzsk2 can you try this syntax? 
```
[exclude]
Alacritty = "^$"
```

**Comment by xzsk2** [comment]
> @xzsk2 can you try this syntax?
> 
> ```
> [exclude]
> Alacritty = "^$"
> ```

yes this works as expected

**Comment by xzsk2** [comment]
Sorry to bother but actually Alacritty is not a good example, as every Alacritty may have a title, it's just a convenient test case

Something really useful is `"[Ss]team" = "^$"` to exclude unwanted icons when hovering over certain Steam UI elements

**Comment by cyrinux** [comment]
Ok I update this thx.
