### ISSUE TITLE
Variables in config

### ISSUE THREAD

**Issue by RikVoorhaar** [cyrinux/hyprland-autoname-workspaces#35]
Instead of having a mapping like 

```
[icons]
"DEFAULT" = "?"
```

It would be really nice to just substitute the class name without icon. To not break previous behavior, I propose to add a `${class}` keyword that gets substituted with the class name (and something similar for title). For example, this would be:
```
[icons]
"DEFAULT" = "${class}"
```

This seems to be a one-line change to the `class_to_icon` method in `mod.rs`. I could draft a PR, but since I am unfamiliar with rust, I suppose someone else could do this much quicker.  GPT-4 suggest the following change, but I haven't tested this:

```rust
#[inline(always)]
fn class_to_icon(&self, class: &str) -> String {
    let cfg = &self.cfg.lock().expect("Unable to obtain lock for config");
    cfg.config
        .icons
        .iter()
        .find_map(|(re_class, icon)| re_class.is_match(class).then(|| icon.replace("${class}", class)))
        .unwrap_or_else(|| {
            if self.args.verbose {
                println!("- window: class '{class}' need a shiny icon");
            }
            cfg.config
                .icons
                .iter()
                .find_map(|(re_class, icon)| (re_class.to_string() == "DEFAULT").then(|| icon.replace("${class}", class)))
                .unwrap_or_else(|| class.to_owned()) // Use the classname when no match is found
        })
}
```

What do you think?

**Comment by cyrinux** [comment]
Looks a good idea. Will think to this 👍

**Comment by cyrinux** [comment]
This is done, I hope you will like. Thanks for the idea. 🧁
