### ISSUE TITLE
Showing count of deduplicated icons

### ISSUE THREAD

**Issue by psimovec** [cyrinux/hyprland-autoname-workspaces#37]
**Is your feature request related to a problem? Please describe.**
--dedup argument saves space on the bar, but we lose information about how many windows are open. I like to keep the information about window count, so I don't use --dedup, but it takes more space this way... 

**Describe the solution you'd like**
- Visually showing count indicator for each icon that has been deduplicated. (For example small number above the icon, or possibly 1 dot for each window)

- Command line argument argument, that would enable this behavior.

**Describe alternatives you've considered**
- Closing some windows because at such point I have probably too many windows open 😂

**Additional context**
Thanks for this "toy"/app, it's pretty useful for me.

**Comment by cyrinux** [comment]
Thanks for the issue, I will study what I can do. I think easiest/possible is to put the counter between parenthesis on the right side.

**Comment by psimovec** [comment]
I tested it out a bit, and icon+thin space+superscripted number looks nice "some icon character ⁴", it is also solution just using text characters and takes less space. Without the thin space it goes over the icon.. But if the superscripted number could be of different color, then it  would work well without the thin space.
![image](https://user-images.githubusercontent.com/52415835/234190190-d3f5f290-c582-470e-8048-8a32f96a623a.png)

**Comment by cyrinux** [comment]
Thanks for the tests!

**Comment by cyrinux** [comment]
Hi @psimovec ,
I find some time to try to implement the feature.
Can you try this PR please ? https://github.com/cyrinux/hyprland-autoname-workspaces/pull/39

**Comment by cyrinux** [comment]
@psimovec please find the new release here https://github.com/cyrinux/hyprland-autoname-workspaces/releases/tag/0.4.4

You have to just add `dedup = true` in your config file. The params `--dedup` and `--counter` are deprecated now.

**Comment by psimovec** [comment]
Thank you @cyrinux ! I tested it, the feature works as expected for me for normal usage. I found a way how to crash the program, but it happens when I have a client that is in depth 17+ in dwindle layout, so I think it is not considered as normal usage :D It might also be a bug of Hyprland instead. If you were interested in looking into that, I was taking notes when testing:  



I reinstalled it using `cargo install --locked hyprland-autoname-workspaces`, it gave me version 1.43 for now, I guess I have to try different way to install. 
For testing purposes I have opened a lot of terminals, it worked until 17 duplicated clients on one screen
```
./hyprland-autoname-workspaces -d -c
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid value: integer `-1`, expected u16", line: 510, column: 18))', /home/psimovec/.cargo/registry/src/github.com-1ecc6299db9ec823/hyprland-autoname-workspaces-0.4.3/src/renamer/mod.rs:32:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried to install hyprland-autoname-workspaces-git using paru/yay and installation  succeeded for me this time.

I realised it was a ~~coincidence~~ that it happened at 17 opened windows, 
with version hyprland-autoname-workspaces-git-0.4.4.r0.g09a64e3-1
I got again the same error at ~88 windows :D 
> hyprland-autoname-workspaces
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid value: integer `-1`, expected u16", line: 2574, column: 18))', src/renamer/mod.rs:32:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

~~It seems like the real issue is, that when I open windows too fast~~, hyprland returns number of windows as -1 or something like that, based on the backtrace.. 

Now I was able to make hyprland-autoname-workspaces crash on start..
```
hyprctl workspaces
workspace ID 1 (1:  ) on monitor eDP-1:
	windows: 2
	hasfullscreen: 0
	lastwindow: 0x562821b89d10
	lastwindowtitle: vim prezentace.txt

workspace ID 2 (2: ) on monitor eDP-1:
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x5628228107c0
	lastwindowtitle: * papir03.pdf — Mozilla Firefox

workspace ID 3 (3: ) on monitor eDP-1:
	windows: 1
	hasfullscreen: 0
	lastwindow: 0x562822a58ca0
	lastwindowtitle: papir03.pdf — Mozilla Firefox

workspace ID 4 (4:   ) on monitor eDP-1:
	windows: 3
	hasfullscreen: 0
	lastwindow: 0x562823d7cdc0
	lastwindowtitle: hyprctl workspaces

workspace ID 5 (5: ¹⁶) on monitor eDP-1:
	windows: 21
	hasfullscreen: 0
	lastwindow: 0x5628242d3b70
	lastwindowtitle: psimovec@bramborka:~


> hyprland-autoname-workspaces
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid value: integer `-1`, expected u16", line: 534, column: 18))', src/renamer/mod.rs:32:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


Oh okay the crash happens when there exists a client with depth>16 in dwindle layout. So the crash is easily reproducible by.
1. setting up dwindle layout
2. opening 17 terminal windows, always nested (for me it worked by not moving mouse)
Then hyprland-autoname-workspaces crashes, and it crashes even on startup.

**Comment by cyrinux** [comment]
Oh, will read your full message asap, but first can you reinstall again ? I didn't push on the cargo store. `cargo install --locked hyprland-autoname-workspaces`. You should have version 0.4.4.

**Comment by cyrinux** [comment]
@psimovec Can you restart the program with a full traceback please, and send me this full backtrace ? ```RUST_BACKTRACE=full hyprland-autoname-workspaces``` ?

**Comment by psimovec** [comment]
```
RUST_BACKTRACE=full hyprland-autoname-workspaces
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid value: integer `-1`, expected u16", line: 558, column: 18))', src/renamer/mod.rs:32:38
stack backtrace:
   0:     0x55a9e03c58da - <unknown>
   1:     0x55a9e03e6c5e - <unknown>
   2:     0x55a9e03c2be5 - <unknown>
   3:     0x55a9e03c56a5 - <unknown>
   4:     0x55a9e03c6e5f - <unknown>
   5:     0x55a9e03c6b9b - <unknown>
   6:     0x55a9e03c7408 - <unknown>
   7:     0x55a9e03c7309 - <unknown>
   8:     0x55a9e03c5d46 - <unknown>
   9:     0x55a9e03c7012 - <unknown>
  10:     0x55a9e0250893 - <unknown>
  11:     0x55a9e0250d43 - <unknown>
  12:     0x55a9e028837b - <unknown>
  13:     0x55a9e02b2259 - <unknown>
  14:     0x55a9e02a5c2e - <unknown>
  15:     0x55a9e02a9058 - <unknown>
  16:     0x55a9e0258b73 - <unknown>
  17:     0x55a9e0293497 - <unknown>
  18:     0x55a9e0259ff3 - <unknown>
  19:     0x55a9e0258f29 - <unknown>
  20:     0x55a9e03bda1c - <unknown>
  21:     0x55a9e0293e75 - <unknown>
  22:     0x7f851dbec790 - <unknown>
  23:     0x7f851dbec84a - __libc_start_main
  24:     0x55a9e0250e85 - <unknown>
  25:                0x0 - <unknown>
```

**Comment by cyrinux** [comment]
Thanks but we miss debug symbol, pacman strip it. If you can git clone the repo, and then `RUST_BACKTRACE=full cargo run` in it, it should be more useful. If you can't I will continue this evening. 😉

**Comment by cyrinux** [comment]
Thanks, perfect, will open a PR to fix the lib.

**Comment by cyrinux** [comment]
@psimovec the PR is open upstream. I will be able to update the toy when it will be merge and release.

**Comment by cyrinux** [comment]
I will close this issue as we drift and open another
