### ISSUE TITLE
[BUG] on-click doesn't work when name includes non-alpha character

### ISSUE THREAD

**Issue by ehula** [cyrinux/hyprland-autoname-workspaces#44]
**Describe the bug**
I have the workspaces module set to activate the workspace on-click. I believe this is the default. While using hyprland-autoname-workspaces, if one or more of the windows on a workspace uses a glyph other that a-z, A-Z, the on-click behaviour no longer works.

**To Reproduce**
1. Configure wlr/workspaces to 'activate' on-click
2. Configure hyprland-autoname-workspaces to use a non-alpha character of a specific application
3. Go to an empty workspace
4. Open that application
5. Move to another workspace
6. Click on the workspace button with the newly launched application
7. Hyprland does not activate and switch to that workspace

**Expected behavior**
Hpyrland should activate and switch to the workspace when the workspace button is clicked.

**Linux Distro (please complete the following information):**
 - NixOS - unstable

**Program version?
 - 0.4.3

**Comment by cyrinux** [comment]
Hi @ehula ,
Thanks for the good report. I'm pretty sure I already have this bad behavior but I can't reproduce it everytime.
I also use waybar-hyprland with this `wlr/workspaces`. I'm not 100% sure its related to this toy but it can be.
Using right now my dev branch and I can reproduce the problem too. I feel like its only the workspace 1 that is not clickable. Is it the case for you too ?

**Comment by cyrinux** [comment]
Can you define "a non-alpha character of a specific application" in your case? (to be sure)

**Comment by ehula** [comment]
For me, the problem occurs on every workspace.

So, after further testing, it seems that the problem is caused when the last character of a window's name is a space character.

**Comment by cyrinux** [comment]
@ehula I comment the AUR package with the new patch to use. You can take it for Nix. 

https://aur.archlinux.org/packages/waybar-hyprland-git#comment-912717

I will *try* to make all this stuff upstream.

🍒
