### ISSUE TITLE
Crash with too many windows.

### ISSUE THREAD

**Issue by pbosab** [cyrinux/hyprland-autoname-workspaces#8]
Hello,

received this error after opening too many windows:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid value: integer `-2`, expected u16", line: 284, column: 15))', src/main.rs:110:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

log with RUST_BACKTRACE=full :

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SerdeError(Error("invalid value: integer `-2`, expected u16", line: 284, column: 15))', src/main.rs:110:38
stack backtrace:
   0:     0x55ee3568447a - <unknown>
   1:     0x55ee356a5c8e - <unknown>
   2:     0x55ee35681885 - <unknown>
   3:     0x55ee35684245 - <unknown>
   4:     0x55ee35685a2f - <unknown>
   5:     0x55ee3568576b - <unknown>
   6:     0x55ee3568613c - <unknown>
   7:     0x55ee35685ed9 - <unknown>
   8:     0x55ee3568492c - <unknown>
   9:     0x55ee35685be2 - <unknown>
  10:     0x55ee3554e923 - <unknown>
  11:     0x55ee3554edb3 - <unknown>
  12:     0x55ee3556722b - <unknown>
  13:     0x55ee35555437 - <unknown>
  14:     0x55ee3558e67f - <unknown>
  15:     0x55ee35581bba - <unknown>
  16:     0x55ee355650d2 - <unknown>
  17:     0x55ee3555afb3 - <unknown>
  18:     0x55ee3555b2e9 - <unknown>
  19:     0x55ee3567ce8c - <unknown>
  20:     0x55ee35568ff5 - <unknown>
  21:     0x7fcddf633790 - <unknown>
  22:     0x7fcddf63384a - __libc_start_main
  23:     0x55ee3554eef5 - <unknown>
  24:                0x0 - <unknown>
```

if you restart the program with many windows already opened, it just crash with the same error.
in my case the number of windows is 15

Thank you.

**Comment by cyrinux** [comment]
Thanks for the issue, wow! I will try to reproduce and fix.

**Comment by cyrinux** [comment]
@pbosab thanks for the report, I open a PR to fix the bug on the hyrpland-rs I use here.

![image](https://user-images.githubusercontent.com/519083/221374865-80f92cb6-4371-4f45-8531-a64f5a38b1af.png)

**Comment by pbosab** [comment]
that was fast! thank you!

**Comment by cyrinux** [comment]
Sadly we find another bug so the good patch to upstream will be longer, or maybe hyprland to patch. We will use my fork of hyprland-rs the time we find a better patch.

**Comment by cyrinux** [comment]
@pbosab I update the pkgbuild and push a Cargo.toml (and Cargo.lock)

Please tell me if this works well now.

A proper fix still have to be done, I will close this issue if this is ok for you.

**Comment by pbosab** [comment]
@cyrinux yup, just tested and is working. thanks a lot.
