### ISSUE TITLE
update to hyprland-rs 0.3.1 when available

### ISSUE THREAD

**Issue by cyrinux** [cyrinux/hyprland-autoname-workspaces#9]
this will fix this log polution due to missing activewindowv2 even in the previous release.

```
$ cargo r
   Compiling hyprland-autoname-workspaces v0.2.12 (/home/cyril.homedir/library/src/personal/github.com/cyrinux/hyprland-autoname-workspaces)
    Finished dev [unoptimized + debuginfo] target(s) in 1.62s
     Running `target/debug/hyprland-autoname-workspaces`
A unknown event was passed into Hyprland-rs
PLEASE MAKE AN ISSUE!!
The event was: (Unable to get)
A unknown event was passed into Hyprland-rs
PLEASE MAKE AN ISSUE!!
The event was: (Unable to get)
A unknown event was passed into Hyprland-rs
PLEASE MAKE AN ISSUE!!
The event was: (Unable to get)
```

**Comment by yavko** [comment]
> this will fix this log polution due to missing activewindowv2 even in the previous release.
> 
> ```
> $ cargo r
>    Compiling hyprland-autoname-workspaces v0.2.12 (/home/cyril.homedir/library/src/personal/github.com/cyrinux/hyprland-autoname-workspaces)
>     Finished dev [unoptimized + debuginfo] target(s) in 1.62s
>      Running `target/debug/hyprland-autoname-workspaces`
> A unknown event was passed into Hyprland-rs
> PLEASE MAKE AN ISSUE!!
> The event was: (Unable to get)
> A unknown event was passed into Hyprland-rs
> PLEASE MAKE AN ISSUE!!
> The event was: (Unable to get)
> A unknown event was passed into Hyprland-rs
> PLEASE MAKE AN ISSUE!!
> The event was: (Unable to get)
> ```

Do you want me to make it a flag that can be disabled?

**Comment by cyrinux** [comment]
Good idea @yavko

**Comment by yavko** [comment]
> Good idea @yavko

I'll add it to the next release then :)

**Comment by yavko** [comment]
Oh, yeah also this issue is resolved, since I released the update.

**Comment by cyrinux** [comment]
fix in https://github.com/cyrinux/hyprland-autoname-workspaces/pull/29
